Fix Deploy workflow
Fixes #163

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -37,7 +37,25 @@ jobs:
         docker push "$IMAGE_ID:latest"
     - name: Deploy image
       run: |
+        set -euo pipefail
+
+        # Find the full qualified "repo digest" for this image
+        IMAGE_DIGEST="$(
+          docker inspect --format='{{join .RepoDigests "\n"}}' "$IMAGE_ID:latest" \
+            | grep --fixed-strings "$IMAGE_ID" || true
+        )"
+        # Fail if we have none or more than one (as indicated by the presence of whitespace)
+        if [[ -z "$IMAGE_DIGEST" || "$IMAGE_DIGEST" =~ [[:space:]] ]]; then
+          echo "Expected exactly one value in IMAGE_DIGEST, got: $IMAGE_DIGEST"
+          echo
+          echo "Debug info:"
+          set -x
+          docker inspect --format='{{join .RepoDigests "\n"}}' "$IMAGE_ID:latest"
+          exit 1
+        fi
+
+        echo "Deploying to $HOST"
+        echo "dokku git:from-image $APP_NAME $IMAGE_DIGEST"
         ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
         ssh-add - <<< "${{ secrets.DOKKU5_DEPLOY_SSH_KEY }}"
-        SHA=$(docker inspect --format='{{index .RepoDigests 0}}' "$IMAGE_ID:latest")
-        ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@"$HOST" git:from-image "$APP_NAME" "$SHA"
+        ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@"$HOST" git:from-image "$APP_NAME" "$IMAGE_DIGEST"
